/*
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGraphDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(fr.imag.mosig.seacs.roboconf.graphDsl.GraphDslPackage.eINSTANCE);
		return result;
	}
}
