/**
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf.validation;

import fr.imag.mosig.seacs.roboconf.validation.AbstractGraphDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GraphDslValidator extends AbstractGraphDslValidator {
}
