/*
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GraphDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/imag/mosig/seacs/roboconf/parser/antlr/internal/InternalGraphDsl.tokens");
	}
}
