/*
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.imag.mosig.seacs.roboconf.services.GraphDslGrammarAccess;

public class GraphDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GraphDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.imag.mosig.seacs.roboconf.parser.antlr.internal.InternalGraphDslParser createParser(XtextTokenStream stream) {
		return new fr.imag.mosig.seacs.roboconf.parser.antlr.internal.InternalGraphDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Graph";
	}
	
	public GraphDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GraphDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
