/*
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.imag.mosig.seacs.roboconf.ui.internal.GraphDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GraphDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GraphDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GraphDslActivator.getInstance().getInjector(GraphDslActivator.FR_IMAG_MOSIG_SEACS_ROBOCONF_GRAPHDSL);
	}
	
}
