/*
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GraphDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return fr.imag.mosig.seacs.roboconf.ui.internal.GraphDslActivator.getInstance().getInjector("fr.imag.mosig.seacs.roboconf.GraphDsl");
	}
	
}
