/*
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GraphDslUiModule extends fr.imag.mosig.seacs.roboconf.ui.AbstractGraphDslUiModule {
	public GraphDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
