/*
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GraphDslRuntimeModule extends fr.imag.mosig.seacs.roboconf.AbstractGraphDslRuntimeModule {

}
