/**
 * generated by Xtext
 */
package fr.imag.mosig.seacs.roboconf.ui.contentassist;

import fr.imag.mosig.seacs.roboconf.ui.contentassist.AbstractGraphDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GraphDslProposalProvider extends AbstractGraphDslProposalProvider {
}
